version: "2"
services:
  web:
    build:
      context: docker/php/
    volumes:
      - .:/www
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: docker/php/
    command: php artisan queue:work --tries 3
    volumes:
      - .:/www
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  redis:
    image: redis
